#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'enhanced_prompt'
require 'optparse'

$options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"

  opts.on("--debug", "debug") do
    $options[:debug] = true
  end
  opts.on("--tokens", "show tokens") do
    $options[:tokens] = true
  end
  opts.on("--colors", "show predefined colors") do
    $options[:colors] = true
  end
  opts.on("-h","--help", "show help") do
    $options[:help] = true
  end
end.parse!


if $options[:tokens] then
  EnhancedPrompt::Prompt.instance_methods(false).sort.each do |met|
    name = met.to_s
    print EnhancedPrompt.run("%Q|#{name}|.c(:red)+' => '+ #{met} + %|\n|" )
  end
elsif $options[:colors] then
  Rainbow::Color::X11Named.color_names.each{|color|
    print EnhancedPrompt.run{":"+color.to_s+" => "+ "      ".bg(color)+"\n"}
  }
else
  print EnhancedPrompt.run('default')
end

